version: 2
updates:
- package-ecosystem: npm
  directory: "/"
  schedule:
    interval: daily
    time: "04:00"
  open-pull-requests-limit: 10
  ignore:
  - dependency-name: webpack
    versions:
    - 5.18.0
    - 5.19.0
    - 5.20.0
    - 5.20.1
    - 5.20.2
    - 5.21.2
    - 5.22.0
    - 5.23.0
    - 5.24.0
    - 5.24.1
    - 5.24.2
    - 5.24.3
    - 5.24.4
    - 5.25.1
    - 5.26.0
    - 5.26.2
    - 5.26.3
    - 5.27.1
    - 5.27.2
    - 5.28.0
    - 5.30.0
    - 5.31.0
    - 5.31.2
    - 5.32.0
    - 5.33.2
    - 5.34.0
    - 5.35.0
    - 5.35.1
    - 5.36.0
  - dependency-name: y18n
    versions:
    - 4.0.1
    - 4.0.2
  - dependency-name: webpack-cli
    versions:
    - 4.4.0
    - 4.5.0
